name = "atlantic-crossword-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "atlantic_crossword_archive"
database_id = "9d743b22-4838-4025-b350-49a2faf570ca"


[triggers]
crons = [
  "10 4 * * *",
  "10 5 * * *",
  "10 8 * * *"
]
