name = "guardian-weekend-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_weekend_archive"
database_id = "8936d37e-6766-4a6d-a855-be5942e03f06"


[triggers]
crons = [
  "5 23 * * *",
  "5 0 * * *",
  "5 1 * * *"
]
