name = "guardian-weekend-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_weekend_archive"
database_id = "8936d37e-6766-4a6d-a855-be5942e03f06"

[[kv_namespaces]]
binding = "HOT_CACHE"
id = "32a0fe8584bb468e82118bdbf89f4b50"
preview_id = "901229f8a1154d908796f1b809028da5"

[triggers]
crons = [
  "0 0 * * *",
  "30 4 * * *",
  "30 9 * * *"
]
