name = "washington-post-daily-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "washington_post_daily_archive"
database_id = "69e16ac4-c357-409b-b780-4451d2368e8c"


[triggers]
crons = [
  "25 4 * * *",
  "25 5 * * *",
  "25 8 * * *"
]
