name = "guardian-prize-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_prize_archive"
database_id = "5fb5ac31-60a1-460c-b7ac-f0529c667c61"


[triggers]
crons = [
  "5 23 * * *",
  "5 0 * * *",
  "5 1 * * *"
]
