name = "latimes-mini-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "latimes_mini_archive"
database_id = "2d48e3d0-5867-4485-9def-bd7c488a9d1a"


[triggers]
crons = [
  "15 4 * * *",
  "15 5 * * *",
  "15 8 * * *"
]
