name = "usa-today-daily-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "usa_today_daily_archive"
database_id = "7eb9493d-01f0-4d29-91ba-2627ee5b52fc"

[vars]
EXTRA_UPDATE_URLS = "https://usa-today-quick-worker.everyman-5b4.workers.dev/api/update/latest"


[triggers]
crons = [
  "20 4 * * *",
  "20 5 * * *",
  "20 8 * * *"
]
