name = "usa-today-daily-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "usa_today_daily_archive"
database_id = "7eb9493d-01f0-4d29-91ba-2627ee5b52fc"

[[kv_namespaces]]
binding = "HOT_CACHE"
id = "b8c7501d2c7449308078408e4a4d7c50"
preview_id = "1a3c970b3a014a1cbd0441c983d22631"

[triggers]
crons = [
  "0 0 * * *",
  "30 4 * * *",
  "30 9 * * *"
]
