name = "latimes-daily-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "latimes_daily_archive"
database_id = "972113a6-220a-421c-969c-477794ef8a03"


[triggers]
crons = [
  "15 4 * * *",
  "15 5 * * *",
  "15 8 * * *"
]
