name = "guardian-quick-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_quick_archive"
database_id = "913a1452-1769-495f-b2ce-8bdf5d4f41d4"


[triggers]
crons = [
  "5 23 * * *",
  "5 0 * * *",
  "5 1 * * *"
]
