name = "guardian-quiptic-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_quiptic_archive"
database_id = "8bcf13e9-64f8-49a3-ae73-af55ae889520"


[triggers]
crons = [
  "5 23 * * *",
  "5 0 * * *",
  "5 1 * * *"
]
