name = "guardian-cryptic-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_cryptic_archive"
database_id = "7aacda12-29fc-45bb-8da7-f2670ad90df4"

[[kv_namespaces]]
binding = "HOT_CACHE"
id = "447d78d081b146319345fcaaafb523b5"
preview_id = "5688aeb122524784b614ab7db2d70c47"

[triggers]
crons = [
  "0 0 * * *",
  "30 4 * * *",
  "30 9 * * *"
]
