name = "guardian-cryptic-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "guardian_cryptic_archive"
database_id = "7aacda12-29fc-45bb-8da7-f2670ad90df4"


[triggers]
crons = [
  "5 23 * * *",
  "5 0 * * *",
  "5 1 * * *"
]
