name = "washington-post-sunday-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "washington_post_sunday_archive"
database_id = "5812780a-92ac-4ace-8ad1-ac38a270addd"