name = "washington-post-sunday-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "washington_post_sunday_archive"
database_id = "REPLACE_WITH_D1_DATABASE_ID"


[triggers]
crons = [
  "25 4 * * *",
  "25 5 * * *",
  "25 8 * * *"
]
